### PR TITLE
update ccg.bib to latest version (2019.12)

### PR DESCRIPTION
**Pull request by schen149**
The current ccg.bib in this repo is very much outdated. Updating it to the latest version (https://cogcomp.seas.upenn.edu/bib/ccg.bib).

### CODE REVIEW

**Comment by js-sheffield** [comment]
The problem with porting the current web version directly is that there were a number of fixes made to the GitHub one separately while the web one was broken.  If we just want to overwrite them, that's okay; it's just different from what I understood of our plan.  In May you had said you would use the newest output and add to the repo only the accurate entries.  (At the least, you should probably remove the three "extra" publications at the top that we added to the database lest we need them quickly.)

**Comment by js-sheffield** [comment]
Sent too soon; I meant to add that the GitHub diff function (except for the header section) basically just divides the diff in half and thus isn't useful.  Can you diff the two files in a way that would actually help find changes?

**Comment by schen149** [comment]
I will remove the three "extra" publications for now. But ultimately I believe our goal should be trying to sync up the website version and the version here for minimal effort. I think it's a bad practice to make any further modifications to the ccg.bib file directly; instead we should be making corresponding changes in database.   

What I had in mind is that  we should (1) Fix all mistakes in the ccg website database, so that we know everything there is correct. (2) Download the the web version of ccg.bib and add it to here.  

For (1), assuming that everything is correct in the current ccg.bib here, we need to correct ccg website database . As you mentioned, git diff doesn't help. However because all bib entries are in chronological order, you could align the entries in the two versions of ccg.bib by simply pulling up the two files side by side, and (in the database) make corrections to the entries that doesn't match ? 

@HeglerTissot , thoughts?

**Comment by HeglerTissot** [comment]
How many entries are different between each version? If the number is low, we can use a simple text diff in order to figure out the differences and populate the website database properly.

**Comment by js-sheffield** [comment]
Well, we started on a plan to fix the database table with the authors spreadsheet that you made and I worked on populating in September.  I then asked Dan a question about it, and he responded last week; I haven't gotten back to it yet.  Let's see whether I can get that done today or tomorrow, and you can make the replacements.  That in itself will clear up a lot of the differences.

I don't actually know how many entries are different between the web version and the GitHub version.  Certainly all the entries since May of 2018 exist only in the web version.  Farther back, I'm not sure how many changes Shyam made in the GitHub version, and since I was making some of them at the same time in the database, there isn't a clear demarcation.

As for diffing the files, I talked to Sihao briefly this afternoon, and I agreed that we could go forward with the overwrite, since we could go back and check Shyam's version from an earlier commit later on.  So let me see what I can do.  Sihao, you can go ahead and merge the overwrite (minus the three extra entries) if you want to make sure it's up do date soonest, or you can wait to see whether we can get this database update finished.

**Pull request merged**
